---
sidebar: sidebar 
permalink: task-blob-enable-data-services.html 
keywords: blob storage, blob working environment, azure blob storage accounts, azure blob working environment, system 
summary: NetApp Console 에서 Azure Blob 스토리지 계정을 검색한 후에는 NetApp 데이터 서비스를 사용하여 백업, 계층화 및 데이터 동기화를 수행할 수 있습니다. 
---
= Azure Blob 스토리지와 함께 NetApp 데이터 서비스 사용
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console 에서 Azure Blob 스토리지 계정을 검색한 후에는 NetApp 데이터 서비스를 사용하여 백업, 계층화 및 데이터 동기화를 수행할 수 있습니다.

* * NetApp Backup and Recovery*를 사용하여 온프레미스 ONTAP 및 Cloud Volumes ONTAP 시스템의 데이터를 Azure Blob 스토리지로 백업합니다.
+
시작하려면 시스템 페이지로 이동하세요.  온-프레미스 ONTAP 또는 Cloud Volumes ONTAP 시스템을 Azure Blob Storage 시스템으로 끌어서 놓습니다.

+
https://docs.netapp.com/us-en/data-services-backup-recovery/concept-ontap-backup-to-cloud.html["ONTAP 데이터를 Azure Blob 스토리지에 백업하는 방법에 대해 자세히 알아보세요."^] .

* * NetApp Cloud Tiering*을 사용하여 온프레미스 ONTAP 클러스터의 비활성 데이터를 Azure Blob 스토리지로 계층화합니다.
+
시작하려면 시스템 페이지로 이동하세요.  온-프레미스 ONTAP 시스템을 Azure Blob Storage 시스템으로 끌어서 놓습니다.

+
https://docs.netapp.com/us-en/data-services-cloud-tiering/task-tiering-onprem-azure.html["ONTAP 데이터를 Azure Blob 스토리지에 계층화하는 방법에 대해 자세히 알아보세요."^] .

* * NetApp Copy and Sync*를 사용하여 Azure Blob Storage 계정과 데이터를 동기화합니다.
+
시작하려면 시스템 페이지로 이동하세요.  소스 시스템을 대상 시스템으로 끌어다 놓습니다.  Azure Blob Storage 시스템은 소스 또는 대상이 될 수 있습니다.

+
Azure Blob Storage 시스템을 선택한 다음 서비스 패널에서 *복사 및 동기화*를 선택하여 Azure Blob Storage 계정과 데이터를 동기화할 수도 있습니다.

+
https://docs.netapp.com/us-en/data-services-copy-sync/concept-cloud-sync.html["복사 및 동기화에 대해 자세히 알아보세요"^] .


